### ISSUE TITLE
[Bug] Unable to create index with date math

### ISSUE THREAD

**Issue by hp0620** [elastic/terraform-provider-elasticstack#105]
**Describe the bug**

Create an index using date math
```
resource "elasticstack_elasticsearch_index" "my-index" {
name = "my-index-{now/d}-000001"

alias {
name = "my-index"
is_write_index = true
}
}
```

Terraform throws an error 
```
Error: invalid value for name (must contain lower case alphanumeric characters and selected punctuation, see: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#indices-create-api-path-params)
│
│ with elasticstack_elasticsearch_index.my-index,
│ on my-index_index.tf line 21, in resource "elasticstack_elasticsearch_index" "my-index":
│ 21: name = "my-index-{now/d}-000001"
│

```

**Expected behavior**
An index gets created and bootstrapped without any error

**Comment by Crazybus** [comment]
Can you provide a curl command showing this works without using Terraform?

According to the docs it is not possible to create an index with date math in the name: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#indices-create-api-path-params. And the error message looks to be correctly showing this.

Instead it looks like you need to add the date math as part of the alias instead https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#indices-create-api-request-body

It would need to look something like (not tested):

```terraform
resource "elasticstack_elasticsearch_index" "my-index" {
	name = "my-index"

	alias {
		name = "my-index-{now/d}-000001"
		is_write_index = true
	}
}
```

**Comment by hp0620** [comment]
Thanks, I do have a quick question, though. 

If the constraint is coming from the special character, then using the url encoding should work, as this commands work in curl and using the kibana dev console. 

```
curl -k -u un:pw -XPUT https://<host:port>/%3Ctestindex-%7Bnow%2Fd%7D-000001%3E
```
However, using the url encoding still does not allow the index to be created. 

```
resource "elasticstack_elasticsearch_index" "testindex" {
name = "%3Ctestindex-%7Bnow%2Fd%7D-000001%3E"

alias {
name = "testindex"
is_write_index = true
}
}

│ Error: invalid value for name (must contain lower case alphanumeric characters and selected punctuation, see: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#indices-create-api-path-params)
│
│ with elasticstack_elasticsearch_index.testindex,
│ on testindex.tf line 21, in resource "elasticstack_elasticsearch_index" "testindex":
│ 21: name = "%3Ctestindex-%7Bnow%2Fd%7D-000001%3E"
│
```
 
If create index api takes that parameter, my understanding is that it should be passed to the .tf file as well. Is there anything that I am missing?

**Comment by Crazybus** [comment]
Thanks for providing the curl command, I understand what you are trying to do now.

The workflow of using Elasticsearch to dynamically name the index using datemath isn't compatible with the way Terraform works. If you create an index doing this Terraform will detect a drift and destroy/recreate the index every time that Terraform is being applied because the name does not match the one that is configured in Terraform. Terraform resources need to have a stable name identifier for its state system to be able to manage their lifecycle properly.

So while the regex could be updated to allow datemath here I don't think it would be possible to support without implementing Elasticsearch datemath logic in the Terraform provider itself. Or updating the state logic to be able to handle this specific use case which would be a bit tricky. However this is something the project maintainers would need to comment on if this is something they would be willing to implement.

If it is truly desirable that you want a new daily index to be created/destroyed on a daily basis with Terraform you would want to calculate the date in Terraform instead like this:

```terraform
resource "elasticstack_elasticsearch_index" "my-index" {
	name = "my-index-${formatdate("YYYY.MM.DD", timestamp())}-000001"

	alias {
		name = "my-index"
		is_write_index = true
	}
}
```

---

Could you explain in a bit more detail what the use case is for this? It sounds like it would be better to use [Index Lifecycle Management](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-lifecycle-management.html) if you want daily indices with rollover.  The `000001` suffix used in the example is a little bit confusing too since that is exactly how ILM names the indices during rollover.

**Comment by hp0620** [comment]
Thanks a lot for the explanation, @Crazybus!

The ILM is in place. Just wanted to bootstrap the index. Yes, that format worked. 

Thanks for the additional information on the volatility of the terraform creation. Was not aware of the destruction aspect, which makes terraform not as viable solution to automate the creation of indices and updating them. 

So as of now, the application of terraform is geared toward initial creation of objects, rather than to update the objects with subsequent changes?

**Comment by Crazybus** [comment]
> The ILM is in place. Just wanted to bootstrap the index. Yes, that format worked.

Apologies for asking again, but could you please provide more information on what you are trying to achieve?

Are you maybe referring to this step in the ILM tutorial? https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-index-lifecycle-management.html#ilm-gs-alias-bootstrap

If you follow those documents it will work as expected as there is no datemath being used to generate the index name. Terraform will be able to bootstrap the initial index and it won't destroy it because the name isn't being dynamically generated by Elasticsearch.

> Thanks for the additional information on the volatility of the terraform creation. Was not aware of the destruction aspect, which makes terraform not as viable solution to automate the creation of indices and updating them.
> So as of now, the application of terraform is geared toward initial creation of objects, rather than to update the objects with subsequent changes?

Terraform is perfectly suited toward creating and updating objects. The issue here is that you are asking Elasticsearch to rename the index which is not something that is supported by Elasticsearch. The Terraform provider is aware of the fact that it cannot update the index name so it correctly destroys the old index and creates a new one with the new name.

**Comment by hp0620** [comment]
Thanks a lot for the input. 

I opened this ticket on behalf of another user who was trying to automate the alias creation through terraform. 

I have not verified the full use case yet on the needs of creating the alias separately this way, so I will have to discuss this with the other user. 

Fully understood that dynamic index creation is not yet viable through terraform. Will validate the use case and update here or open another one if needed. 

Thanks for the help!
