### ISSUE TITLE
[Feature] roadmap for futur releases ?

### ISSUE THREAD

**Issue by fludo** [elastic/terraform-provider-elasticstack#134]
Sorry for opening an issue for it but I cannot find someone to answer my question on discuss.elastic.co: https://discuss.elastic.co/t/terraform-elasticstack-provider-features-and-roadmap/309623

We are expecting many new features to be available on 0.4.0 (TBR) or future releases: Kibana ressources, role mapping.
I also have opened a feature request for script/search template support [[Feature] Support for search templates / stored scripts · Issue #107 · elastic/terraform-provider-elasticstack · GitHub 1](https://github.com/elastic/terraform-provider-elasticstack/issues/107)

However, since march 2022, the activity seems to have totally dropped on this project and no new version have been released. [Code frequency · elastic/terraform-provider-elasticstack (github.com) 1](https://github.com/elastic/terraform-provider-elasticstack/graphs/code-frequency)

Are there some insights about what feature to expect in the upcoming months ?

Can you publish a roadmap somewhere so we know if we better implement manual api call or wait for a future release to support it through terraform ?

**Comment by Kushmaro** [comment]
@fludo , upcoming roadmap items are communicated via the milestone section of this project. We don't communicate timelines for these, as of yet. 

I'll be closing this issue as the milestone section we'll reflect everything we intend to work on. The reason regular development had ceased for a while was due to a shift in priorities and working teams on this. But it should resume shortly enough.

closing this ticket.

**Comment by fludo** [comment]
@Kushmaro Thanks for your reply, I hope it will resume soon since they are few key feature that are missing to fully deploy our assets "as code" with terraform.
