### ISSUE TITLE
[Feature] Support AWS auth

### ISSUE THREAD

**Issue by dm3ch** [elastic/terraform-provider-elasticstack#243]
**Is your feature request related to a problem? Please describe.**
When I trying to use this provider with AWS hosted ES cluster the AWS signer auth support lacks, which makes hard to use this provider in such cases.

**Describe the resource you would like to have implemented.**
None

**Describe the solution you'd like**
Adding AWS auth support to provider

**Describe alternatives you've considered**
Currently I'm running local proxy (which implements requests signing)

**Additional context**

**Comment by Cristigeo** [comment]
> AWS hosted ES cluster

If that means AWS OpenSearch, I believe this provider might not be the best fit, because it is built upon the [elastic go client](https://github.com/elastic/go-elasticsearch), which in turn is tailored to the Elasticsearch API specifications. Technically, the support for AWS SigV4 should be added in the elastic client code, not in the terraform provider code, and I'm not sure the maintainers of the elastic client would consider supporting AWS. Furthermore, even assuming the AWS signer would be added, there's no compatibility guarantee for the two APIs (Elasticsearch and OpenSearch).

**Comment by tobio** [comment]
^ this. I'm closing this out as there's no plans to put this on a roadmap.
