### ISSUE TITLE
[Feature] Support for Alerts

### ISSUE THREAD

**Issue by RobDTech** [elastic/terraform-provider-elasticstack#48]
Having the ability to add and maintain alerts

**Comment by RobDTech** [comment]
https://www.elastic.co/guide/en/kibana/master/alerting-apis.html
Create/Update/Delete

**Comment by acrewdson** [comment]
+1, would be really helpful

**Comment by nicholastucker** [comment]
+2, would be great!

**Comment by nbs-rsutton** [comment]
+3, would be very helpful!

**Comment by alexlafreniere** [comment]
+4, this would be amazing for us

**Comment by nicholas-r-king** [comment]
+5 we really need this.

**Comment by cjr125** [comment]
+6 please support

**Comment by cerdman** [comment]
+1 please add support

**Comment by chanlawrencet** [comment]
+1 support for this would be a great help!

**Comment by kryspetrie** [comment]
+1 PLEASE. Our support team really needs this!

**Comment by rodya-mirov** [comment]
+1, This would be a big help for us, would appreciate any updates

**Comment by hdeweirdt** [comment]
+1 great help for us

**Comment by timmatsam** [comment]
+1 would greatly appreciate support for this

**Comment by aleedom** [comment]
+1 could really use this feature for our workflow.

**Comment by ModeEngage** [comment]
Would be great to use tools we already utilize to create our alerts!

**Comment by jordan-donovan** [comment]
+1 this would be great for our team

**Comment by mandragorn** [comment]
+1 this would really help reduce the load on our engineering support team.

**Comment by desaip01** [comment]
+1 would greatly appreciate support for this

**Comment by eczernikowski** [comment]
+1 please support really need this!

**Comment by RobsonSutton** [comment]
@Kushmaro / @olksdr - I started taking a look at building this out the other day due to the level of demand from different people, but I couldn't seem to find an elastic supported go client for the Kibana API... I can see the elasticsearch one that is currently being used (https://github.com/elastic/go-elasticsearch). Please can you advise on the plan for delivering any of the Kibana based functionality via terraform? Is the plan to create a new repo for this client as is in place for elasticsearch, or are you looking to bake this into this repo somehow? If a new repo is being built for this, is this something we are able to contribute to in order to help speed up the delivery of the kibana functionality in this one?

Also, I'm assuming any Kibana based functionality will be blocked until this client can be built?

P.S. Still new to the Go / TF provider building world so please correct me if my understanding on any of the above is incorrect!

**Comment by aydasraf** [comment]
+1 would greatly appreciate support for this! Any ETA on the release of this feature to plan the engineering work accordingly?

**Comment by webfella** [comment]
> +1 would greatly appreciate support for this! Any ETA on the release of this feature to plan the engineering work accordingly?

@aydasraf It's currently planned to release by the end of Jan mate, we'll be submitting an API to https://github.com/disaster37/go-kibana-rest followed by TF support here. I'm happy to give you a ping when it's released.

**Comment by aydasraf** [comment]
> > +1 would greatly appreciate support for this! Any ETA on the release of this feature to plan the engineering work accordingly?
> 
> @aydasraf It's currently planned to release by the end of Jan mate, we'll be submitting an API to https://github.com/disaster37/go-kibana-rest followed by TF support here. I'm happy to give you a ping when it's released.

@webfella Thank you mate for the update! Just at the right time for us. I am watching the releases, but would also appreciate the ping. Wish you, a merry Christmas and a wonderful and happy new year.

**Comment by benjyabr** [comment]
Thanks for the merge!
As support for alerts has just added, when do we expect the release of 0.6.0?

**Comment by jsangilve** [comment]
Sorry for pinging @tobio — and thank you for adding support for alerting— but following @benjyabr's question, when do you plan to release the new version including #292?

**Comment by tobio** [comment]
We're also looking to add support for managing alert connectors in a 0.6 release. I'd expect sometime in April.

**Comment by RobDTech** [comment]
Hi, any update on the release of 0.6.0 please?

**Comment by dimuon** [comment]
Hi @RobDTech , 0.6.0 was released today
