### ISSUE TITLE
[Bug] elasticstack_kibana_alerting_rule cannot accept an empty notify_when parameter

### ISSUE THREAD

**Issue by othmane399** [elastic/terraform-provider-elasticstack#480]
**Describe the bug**

Hello,
I'm importing some ES siem rules into IaC using `elasticstack_kibana_alerting_rule` and there's an issue with the `notify_when` parameter.

Here's the notify_when parameter of the created rule from UI:

```
GET kbn:/api/alerting/rule/bcd0ed80-0e9c-11ee-a735-c93aa3d264ad
{
 "id": "bcd0ed80-0e9c-11ee-a735-c93aa3d264ad",
  "name": "XYZ",
  "tags": [],
  "consumer": "siem",
  "enabled": true,
  "schedule": {
    "interval": "30m"
  },
  "notify_when": null,
  ....
```

The provider set the `notify_when` parameter [as required](https://registry.terraform.io/providers/elastic/elasticstack/0.9.0/docs/resources/kibana_alerting_rule#notify_when)
so to fix the issue, I set notify_when to `onActiveAlert` on the code, which is not needed to make the rule works from UI.

**To Reproduce**
Just create a SIEM rule from UI and try to import it using the json format or `terraform plan -generate-config-out=generated.tf`

**Expected behavior**
`notify_when` can be `null` for `siem` rules at least

**Versions (please complete the following information):**
 - OS: Linux
 - Terraform Version 1.5.6
 - Provider version 0.10.0
 - Elasticsearch Version 8.10.3

**Additional context**
N/A

**Comment by dejongm** [comment]
I tried to address this with my limited go knowledge, but this is falls outside the scope of my abilities. I did get as far as just setting the value for `notify_when` to null to see what it would do. It then complained that  the actions were missing `frequency` parameters. I'm guessing this is a result of a change in the API from 7 to 8?

**Comment by jpdjere** [comment]
Hi @othmane399 @dejongm cc @111andre111 

In the [Security Solution](https://www.elastic.co/guide/en/security/current/rules-api-create.html), we do not use the mentioned parameter `notify_when` on a rule level. Since 8.8 users should use the actions-level [frequency](https://www.elastic.co/guide/en/security/current/rules-api-create.html#optional-actions-fields-rule-create) parameter.

Our official recommendation is to use the [Security Solution's Detections API for creating Security Rules.](https://www.elastic.co/guide/en/security/current/rules-api-create.html)

The Terraform provider uses the [Alerting API to create rules](https://www.elastic.co/guide/en/kibana/current/create-rule-api.html), and while it is possible to use that API to create Security Rules, it is not officially supported or recommended. Therefore, the Terraform provider should not be used to create Security Rules either. Please use our the Detections API instead.

**Comment by othmane399** [comment]
Hello @jpdjere, 

Thanks for your answer.

Should I create an issue mentioning a feature request to have a new terraform resource for detection api or can we just update this one ?

**Comment by jpdjere** [comment]
@othmane399 Please create a new feature request ticket and close this one, if your doubt has been resolved.

**Comment by dejongm** [comment]
Hello @othmane399 , My issue does not involve the security solution. My issue is with creating/maintaining an alerting rule in cluster management. Should I open another issue? It will have more or less the same title.

**Comment by jpdjere** [comment]
@dejongm Yes, please open a separate issue.

**Comment by dejongm** [comment]
New issue opened #524 to address issue in cluster management alerting rules

**Comment by cnasikas** [comment]
Fixed by https://github.com/elastic/kibana/issues/186963. Starting from [v0.11.7](https://github.com/elastic/terraform-provider-elasticstack/releases/tag/v0.11.7), the Rule resource now supports the rule's `alert_delay` property and the rule's action `alerts_filter` and `frequency` properties. You can find complete documentation on the Elastic Terraform provider [documentation page](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/kibana_alerting_rule).
