### ISSUE TITLE
Need to attach ILM policy while creating an index template[Feature]

### ISSUE THREAD

**Issue by sidharthvijayakumar** [elastic/terraform-provider-elasticstack#65]
**Is your feature request related to a problem? Please describe.**
When I create a index template I have a requirement to attach ILM policy in the settings but am unable to do that
![Error I am getting when I try to attach an existing ILM policy to index template]()

**Comment by olksdr** [comment]
hey @sidharthvijayakumar  can you post the error you get and the configuration you use to provide the ILM policy in the settings?

**Comment by sidharthvijayakumar** [comment]
Hi got this error when I tried to apply 

terraform apply
╷
│ Error: Reference to undeclared resource
│ 
│   on main.tf line 14, in resource "elasticstack_elasticsearch_index_template" "temp":
│   14:       lifecycle.name = "sdid"
│ 
│ A managed resource "lifecycle" "name" has not been declared in the root module.


This is how I have declared the ilm policy :

resource "elasticstack_elasticsearch_index_template" "temp" {

  name = var.NAME
  priority = var.PRIORITY
  index_patterns = var.INDEX_PATTERNS
  composed_of = var.COMPONENT_TEMPLATES
  data_stream {}
  template {
    alias {
      name = var.ALIAS
    }
    settings = jsonencode({
      number_of_shards = "${var.NUMBER_OF_SHARDS}",
      lifecycle.name = "sdid"
    })   
  }
}

**Comment by olksdr** [comment]
So the error you see is coming from the Terraform. It tries to find the `managed resource` since you're using `lifecycle.name` without quotes. 

Basically in the repos is an example of how you can use it, see
https://github.com/elastic/terraform-provider-elasticstack/blob/6c589279eb1a51fa665a8cae3794fbd8746012b7/examples/resources/elasticstack_elasticsearch_data_stream/resource.tf#L32-L37

Where I set up the ILM policy and then use it in template's settings.
