### ISSUE TITLE
[Bug] synthetics http/tcp monitor produces inconsistent result after apply

### ISSUE THREAD

**Issue by biscout42** [elastic/terraform-provider-elasticstack#800]
**Describe the bug**

For a `http` monitor there are fields populated not as they are set in tf config. ES stack: `8.15.1`

```
produced an unexpected new value: 

.locations[0]: was cty.StringVal("us_east"), but now cty.StringVal("North America - US East").
.http.proxy_url: was null, but now cty.StringVal("")
.http.ssl_supported_protocols: was null, but now cty.ListVal([]cty.Value{cty.StringVal("TLSv1.1"), cty.StringVal("TLSv1.2"), cty.StringVal("TLSv1.3")}).
.http.ssl_verification_mode: was null, but now cty.StringVal("full").

```

**Comment by biscout42** [comment]
Same for `tcp`

**Comment by GuillermoRosello** [comment]
Similar issue with 

- ES Stack 8.14.3
- Provider version v0.11.8
- Terraform v1.5.3

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # elasticstack_kibana_synthetics_monitor.test_uptime is tainted, so must be replaced
-/+ resource "elasticstack_kibana_synthetics_monitor" "test_uptime" {
      ~ id        = "ops/7c31be2c-6cdc-4d7a-a8d7-06e1e1bf2aca" -> (known after apply)
      ~ locations = [
          - "us-west1-a",
          - "us-east4-a",
          + "us_west",
          + "us_east",
        ]
        name      = "test Uptime: enlightedinc.com"
        tags      = [
            "service:test",
            "terraform:yes",
        ]
        # (6 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

elasticstack_kibana_synthetics_monitor.test_uptime: Destroying... [id=ops/7c31be2c-6cdc-4d7a-a8d7-06e1e1bf2aca]
elasticstack_kibana_synthetics_monitor.test_uptime: Destruction complete after 2s
elasticstack_kibana_synthetics_monitor.test_uptime: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to elasticstack_kibana_synthetics_monitor.test_uptime, provider "provider[\"registry.terraform.io/elastic/elasticstack\"]" produced an unexpected new value: .locations[0]: was
│ cty.StringVal("us_west"), but now cty.StringVal("us-west1-a").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to elasticstack_kibana_synthetics_monitor.test_uptime, provider "provider[\"registry.terraform.io/elastic/elasticstack\"]" produced an unexpected new value: .locations[1]: was
│ cty.StringVal("us_east"), but now cty.StringVal("us-east4-a").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.``

Instead of ("North America - US East") it uses ("us-east4-a")

**Comment by biscout42** [comment]
Here is the fix: https://github.com/elastic/terraform-provider-elasticstack/pull/823 .

As a workaround, for values excepts `locations` one could set defaults to the values kibana replies instead of leaving them empty.

For `locations`, due-to https://github.com/elastic/kibana/issues/194901 , monitor import would not work in the current version. I could see that kibana folks already working on the fix 🚀

**Comment by tobio** [comment]
@biscout42 are we able to close this issue?

**Comment by biscout42** [comment]
Yeah, thanks, `v0.11.9` is there 🎉

**Comment by GuilleR-AR** [comment]
It works for me too Thanks
